/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrajetoRouteImport } from './routes/trajeto'
import { Route as RotasRouteImport } from './routes/rotas'
import { Route as RotaRouteImport } from './routes/rota'
import { Route as RelatosRouteImport } from './routes/relatos'
import { Route as NavegacaoRouteImport } from './routes/navegacao'
import { Route as IndexRouteImport } from './routes/index'

const TrajetoRoute = TrajetoRouteImport.update({
  id: '/trajeto',
  path: '/trajeto',
  getParentRoute: () => rootRouteImport,
} as any)
const RotasRoute = RotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaRoute = RotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatosRoute = RelatosRouteImport.update({
  id: '/relatos',
  path: '/relatos',
  getParentRoute: () => rootRouteImport,
} as any)
const NavegacaoRoute = NavegacaoRouteImport.update({
  id: '/navegacao',
  path: '/navegacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/navegacao': typeof NavegacaoRoute
  '/relatos': typeof RelatosRoute
  '/rota': typeof RotaRoute
  '/rotas': typeof RotasRoute
  '/trajeto': typeof TrajetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/navegacao': typeof NavegacaoRoute
  '/relatos': typeof RelatosRoute
  '/rota': typeof RotaRoute
  '/rotas': typeof RotasRoute
  '/trajeto': typeof TrajetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/navegacao': typeof NavegacaoRoute
  '/relatos': typeof RelatosRoute
  '/rota': typeof RotaRoute
  '/rotas': typeof RotasRoute
  '/trajeto': typeof TrajetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/navegacao' | '/relatos' | '/rota' | '/rotas' | '/trajeto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/navegacao' | '/relatos' | '/rota' | '/rotas' | '/trajeto'
  id:
    | '__root__'
    | '/'
    | '/navegacao'
    | '/relatos'
    | '/rota'
    | '/rotas'
    | '/trajeto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NavegacaoRoute: typeof NavegacaoRoute
  RelatosRoute: typeof RelatosRoute
  RotaRoute: typeof RotaRoute
  RotasRoute: typeof RotasRoute
  TrajetoRoute: typeof TrajetoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trajeto': {
      id: '/trajeto'
      path: '/trajeto'
      fullPath: '/trajeto'
      preLoaderRoute: typeof TrajetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotas': {
      id: '/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof RotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota': {
      id: '/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof RotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatos': {
      id: '/relatos'
      path: '/relatos'
      fullPath: '/relatos'
      preLoaderRoute: typeof RelatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navegacao': {
      id: '/navegacao'
      path: '/navegacao'
      fullPath: '/navegacao'
      preLoaderRoute: typeof NavegacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NavegacaoRoute: NavegacaoRoute,
  RelatosRoute: RelatosRoute,
  RotaRoute: RotaRoute,
  RotasRoute: RotasRoute,
  TrajetoRoute: TrajetoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
