/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrajetoRouteImport } from './routes/trajeto'
import { Route as IndexRouteImport } from './routes/index'

const TrajetoRoute = TrajetoRouteImport.update({
  id: '/trajeto',
  path: '/trajeto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trajeto': typeof TrajetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trajeto': typeof TrajetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trajeto': typeof TrajetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trajeto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trajeto'
  id: '__root__' | '/' | '/trajeto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrajetoRoute: typeof TrajetoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trajeto': {
      id: '/trajeto'
      path: '/trajeto'
      fullPath: '/trajeto'
      preLoaderRoute: typeof TrajetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrajetoRoute: TrajetoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
